### ISSUE TITLE
Consider change of direction in minimization algorithm

### ISSUE THREAD

**Issue by hect1995** [XiaojingGeorgeZhang/OBCA#4]
The results of the minimization algorithm for the Parking problem sometimes give unnecessary change of directions as it is not taken into consideration in the IPOPT model (just in the Hybrid A*). Is there any way to include a penalization in the change of direction ? Looking at the state vector and control input I cannot find any way to penalize it

**Comment by alexliniger** [comment]
No this would be a non-differentiable cost because it contains an "if" statement. 
One approach I see would be to increase the cost on the jerk and maybe the acceleration, in the hope that this indirectly fixes the problem. Since stopping and accelerating requires quite a lot of jerk.
Best,
Alex

**Comment by hect1995** [comment]
Thanks, I will try that. Furthermore I have another doubt (I do not know if you prefer that I open a new issue)
I have adapted the map to my requirements and the new map is [0,100,0,100] so a square of 100m. Just by changing this size the hybrid_a_star.jl gives the error:
`ERROR: LoadError: BoundsError: attempt to access 80×44 Array{Float64,2} at index [173, -25]
Stacktrace:
 [1] calc_cost(::hybrid_a_star.Node, ::Array{Float64,0}, ::Array{Float64,2}, ::hybrid_a_star.Node, ::hybrid_a_star.Config) at /home/developer/H-OBCA/hybrid_a_star.jl:550
 [2] calc_hybrid_astar_path(::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::Float64, ::Float64) at /home/developer/H-OBCA/hybrid_a_star.jl:145
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] macro expansion at /home/developer/JuliaPro-0.6.4.1/JuliaPro/pkgs-0.6.4.1/v0.6/Atom/src/repl.jl:118 [inlined]
 [6] anonymous at ./<missing>:?
while loading /home/developer/H-OBCA/main.jl, in expression starting on line 250`
Values change depending on the obstacle analyzed first. I have checked all the obstacles and all vertex seem correct.
The concrete line of code that fails is: 
```
    elseif length(h_dp) > 1 # Distance policy heuristics is activated
        return (n.cost + H_COST*h_dp[n.xind - c.minx, n.yind - c.miny])
```
from the calc_cost function

**Comment by alexliniger** [comment]
This sounds like an issue which could be also interesting for other people. Could you please open a new issue with a new title.
I have to look at the code, I once had a similar issue when I scaled everything to 1:43 scale. If I remember correctly there are several files where you need to change things. But I don't know the hybrid A* code that well, as I did not write it (compared to most of the other code)

**Comment by hect1995** [comment]
Done, thanks
